<<<<<<< HEAD
# Generated by Django 2.2.16 on 2020-11-13 08:33
=======
# Generated by Django 2.2.16 on 2020-11-15 18:16
>>>>>>> 036df3baa4d4ddbeee73bdb37d67032ad9f04bfa

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ('accounts', '0001_initial'),
        ('kiosks', '0003_auto_20201112_1526'),
=======
        ('kiosks', '0002_history_updated_at'),
>>>>>>> 036df3baa4d4ddbeee73bdb37d67032ad9f04bfa
    ]

    operations = [
        migrations.CreateModel(
            name='Recommend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kiosks.Menu')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.User')),
            ],
        ),
    ]
